version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache: # restore the saved cache after the first run or if `pom.xml` has changed
          keys:
            - pms-ui-repo-{{ checksum "package-lock.json" }}

      - run:
          name: Install dependencies with NPM
          command: npm install # replace with `yarn install` if using yarn

      - save_cache: # special step to save the dependency cache
          key: pms-ui-repo-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"

      - run:
          name: Run tests
          # Runs jest with "--maxWorkers=2" argument to avoid OOM issues
          command: npm test # replace with `yarn test` if using yarn